In [ ]:
from pyleotups import NOAADataset
ds=NOAADataset()
df = ds.search_studies(noaa_id=33213)
dfs = ds.get_data(dataTableIDs="45859")
dfs[0].head()

[2026-04-22 16:23:56,928][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:23:56,928][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&NOAAStudyId=33213&limit=100

Parsing NOAA studies:   0%|                                                                            | 0/1 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]

[2026-04-22 16:23:57,762][INFO] - Retrieved 1 studies.

,Site,Hole,Core,Type,Section,Section_Depth,Sample_Depth,Age,TEX86H,SST
0,NaN,NaN,1,NaN,1.0,4.5,0.045,0.31,-0.1177,30.55
1,NaN,NaN,1,NaN,1.0,31.5,0.315,0.66,-0.1216,30.28
2,NaN,NaN,1,NaN,1.0,61.5,0.615,1.04,-0.1183,30.51
3,NaN,NaN,1,NaN,1.0,90.5,0.905,1.41,-0.1089,31.15
4,NaN,NaN,1,NaN,1.0,121.5,1.215,1.80,-0.1155,30.70

In [ ]:
from pyleotups import NOAADataset
ds=NOAADataset()
dsf = ds.search_studies(noaa_id=33213)
df = ds.get_funding()
df.head()

[2026-04-22 16:23:59,207][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:23:59,207][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&NOAAStudyId=33213&limit=100

Parsing NOAA studies:   0%|                                                                            | 0/1 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|███████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 362.48it/s]

[2026-04-22 16:23:59,857][INFO] - Retrieved 1 studies.

,StudyID,StudyName,FundingAgency,FundingGrant
0,33213,"Bay of Bengal, Northeast Indian Margin Stable ...",US National Science Foundation,OCE1634774
1,33213,"Bay of Bengal, Northeast Indian Margin Stable ...",United States Geological Survey (USGS),NE/L002493/1
2,33213,"Bay of Bengal, Northeast Indian Margin Stable ...",UK Natural Environment Research Council (NERC),"JPMXS05R2900001, 19H05595"
3,33213,"Bay of Bengal, Northeast Indian Margin Stable ...",Japan Society for the Promotion of Science (JSPS),JPMXS05R2900001

In [ ]:
from pyleotups import NOAADataset
ds=NOAADataset()
dsf = ds.search_studies(noaa_id=33213)
df = ds.get_geo()
df.head()

[2026-04-22 16:23:59,876][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:23:59,876][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&NOAAStudyId=33213&limit=100

Parsing NOAA studies:   0%|                                                                            | 0/1 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]

[2026-04-22 16:24:00,488][INFO] - Retrieved 1 studies.

,StudyID,DataType,SiteID,SiteName,LocationName,GeoType,GeometryType,MinLatitude,MaxLatitude,MinLongitude,MaxLongitude,MinElevation,MaxElevation
0,33213,PALEOCEANOGRAPHY,58697,IODP U1446,Ocean>Indian Ocean,Feature,POINT,19.083,19.083,85.733,85.733,-1440,-1440

In [ ]:
from pyleotups import NOAADataset
ds=NOAADataset()
dsf = ds.search_studies(noaa_id=33213)
bib, df = ds.get_publications()
df.head()

[2026-04-22 16:24:00,505][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:00,505][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&NOAAStudyId=33213&limit=100

Parsing NOAA studies:   0%|                                                                            | 0/1 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|███████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 495.72it/s]

[2026-04-22 16:24:01,207][INFO] - Retrieved 1 studies.

,Author,Title,Journal,Year,Volume,Number,Pages,Type,DOI,URL,CitationKey,StudyID,StudyName
0,"Clemens, Steven; Yamamoto, Masanobu; Thirumala...",Remote and Local Drivers of Pleistocene South ...,Science Advances,2021,7,23,NaN,publication,10.1126/sciadv.abg3848,http://dx.doi.org/10.1126/sciadv.abg3848,M._Remote_2021_33213,33213,"Bay of Bengal, Northeast Indian Margin Stable ..."

In [ ]:
from pyleotups import NOAADataset
ds=NOAADataset()
df = ds.search_studies(noaa_id=33213)
df.head()

[2026-04-22 16:24:01,242][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:01,250][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&NOAAStudyId=33213&limit=100

Parsing NOAA studies:   0%|                                                                            | 0/1 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]

[2026-04-22 16:24:01,876][INFO] - Retrieved 1 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,33213,74834,"Bay of Bengal, Northeast Indian Margin Stable ...",PALEOCEANOGRAPHY,1462580,280,-1460630,1670,"(19.083, 19.083, 85.733, 85.733)","Provided Keywords: Indian monsoon, South Asian...",None,"Steven Clemens, Masanobu Yamamoto, Kaustubh Th...","[{'Author': 'Clemens, Steven; Yamamoto, Masano...","[[{'DataTableID': '45857', 'DataTableName': 'U...",[{'fundingAgency': 'US National Science Founda...

In [ ]:
from pyleotups import NOAADataset
ds=NOAADataset()
dsf = ds.search_studies(noaa_id=33213)
df = ds.get_tables()
df.head()

[2026-04-22 16:24:01,906][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:01,907][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&NOAAStudyId=33213&limit=100

Parsing NOAA studies:   0%|                                                                            | 0/1 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]

[2026-04-22 16:24:02,596][INFO] - Retrieved 1 studies.

,DataTableID,DataTableName,TimeUnit,FileURL,Variables,FileDescription,SiteID,SiteName,LocationName,GeoType,GeometryType,MinLatitude,MaxLatitude,MinLongitude,MaxLongitude,MinElevation,MaxElevation,StudyID,StudyName
0,45857,U1446 Benthic Isotopes Clemens2021,cal yr BP,https://www.ncei.noaa.gov/pub/data/paleo/contr...,"[Site, d13C, d18O, Age, Sample_Depth, Section_...",NOAA Template File,58697,IODP U1446,Ocean>Indian Ocean,Feature,POINT,19.083,19.083,85.733,85.733,-1440,-1440,33213,"Bay of Bengal, Northeast Indian Margin Stable ..."
1,45864,U1446 Age Model Clemens2021,cal yr BP,https://www.ncei.noaa.gov/pub/data/paleo/contr...,"[Age, Sample_Depth, Comments, Site]",NOAA Template File,58697,IODP U1446,Ocean>Indian Ocean,Feature,POINT,19.083,19.083,85.733,85.733,-1440,-1440,33213,"Bay of Bengal, Northeast Indian Margin Stable ..."
2,45863,U1446 Rb/Ca Clemens2021,cal yr BP,https://www.ncei.noaa.gov/pub/data/paleo/contr...,"[Section, Type, Hole, Site, Rb/Ca, Rb_normaliz...",NOAA Template File,58697,IODP U1446,Ocean>Indian Ocean,Feature,POINT,19.083,19.083,85.733,85.733,-1440,-1440,33213,"Bay of Bengal, Northeast Indian Margin Stable ..."
3,45862,U1446 Mg/Ca Clemens2021,cal yr BP,https://www.ncei.noaa.gov/pub/data/paleo/contr...,"[Mg/Ca_SST, Mg/Ca, Age, Sample_Depth, Section_...",NOAA Template File,58697,IODP U1446,Ocean>Indian Ocean,Feature,POINT,19.083,19.083,85.733,85.733,-1440,-1440,33213,"Bay of Bengal, Northeast Indian Margin Stable ..."
4,45861,U1446 LeafWax CarbonIsotope Clemens2021,cal yr BP,https://www.ncei.noaa.gov/pub/data/paleo/contr...,"[d13C_Ave, d13C_C32, d13C_C30, d13C_C28, d13C_...",NOAA Template File,58697,IODP U1446,Ocean>Indian Ocean,Feature,POINT,19.083,19.083,85.733,85.733,-1440,-1440,33213,"Bay of Bengal, Northeast Indian Margin Stable ..."

In [ ]:
from pyleotups import NOAADataset
ds=NOAADataset()
dsf = ds.search_studies(noaa_id=33213)
df_var = ds.get_variables(dataTableIDs="45859")
df_var.head()

[2026-04-22 16:24:02,638][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:02,638][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&NOAAStudyId=33213&limit=100

Parsing NOAA studies:   0%|                                                                            | 0/1 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]

[2026-04-22 16:24:03,401][INFO] - Retrieved 1 studies.

,StudyID,SiteID,FileURL,VariableName,cvDataType,cvWhat,cvMaterial,cvError,cvUnit,cvSeasonality,cvDetail,cvMethod,cvAdditionalInfo,cvFormat,cvShortName
DataTableID,,,,,,,,,,,,,,,
45859,33213,58697,https://www.ncei.noaa.gov/pub/data/paleo/contr...,SST,CLIMATE RECONSTRUCTIONS|PALEOCEANOGRAPHY,earth system variable>temperature variable>tem...,reconstruction material>organic compound index...,None,temperature unit>degree Celsius,None,None,None,index of Kim et al. 2010,Numeric,SST
45859,33213,58697,https://www.ncei.noaa.gov/pub/data/paleo/contr...,TEX86H,PALEOCEANOGRAPHY,chemical composition>compound>organic compound...,None,None,dimensionless,None,None,laboratory method>chromatography>liquid chroma...,index of Schouten et al. 2002; extracted lipids,Numeric,TEX86H
45859,33213,58697,https://www.ncei.noaa.gov/pub/data/paleo/contr...,Age,CLIMATE RECONSTRUCTIONS|PALEOCEANOGRAPHY,age variable>age,None,None,time unit>age unit>calendar kiloyear before pr...,None,None,None,None,Numeric,Age
45859,33213,58697,https://www.ncei.noaa.gov/pub/data/paleo/contr...,Sample_Depth,CLIMATE RECONSTRUCTIONS|PALEOCEANOGRAPHY,depth variable>depth,None,None,length unit>meter,None,None,None,Spliced core composite depth below sea floor ...,Numeric,Sample_Depth
45859,33213,58697,https://www.ncei.noaa.gov/pub/data/paleo/contr...,Section_Depth,PALEOCEANOGRAPHY,sampling metadata>sample identification,None,None,length unit>centimeter,None,None,None,Mid-depth of sample within section,Numeric,Section_Depth

In [ ]:
import pyleotups as pt
ds = pt.NOAADataset()
df_noaa = ds.search_studies(noaa_id=13156)
df_xml = ds.search_studies(xml_id=1840)
df_noaa.head()
df_xml.head()

[2026-04-22 16:24:03,475][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:03,475][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&NOAAStudyId=13156&limit=100

Parsing NOAA studies:   0%|                                                                            | 0/1 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]

[2026-04-22 16:24:04,078][INFO] - Retrieved 1 studies.

[2026-04-22 16:24:04,084][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:04,084][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&xmlId=1840&limit=100

Parsing NOAA studies:   0%|                                                                            | 0/1 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|███████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 538.28it/s]

[2026-04-22 16:24:04,703][INFO] - Retrieved 1 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,5589,1840,Southern Ocean Midlatitude 160KYr Alkenone SST...,PALEOCEANOGRAPHY,156360,1951,-154410,-1,"(-45.53, -40.37, 174.93, 177.98)",None,[Sea Surface Temperature Reconstruction],"Katharina Pahnke, Julian Sachs","[{'Author': 'Pahnke, K. and J.P. Sachs', 'Titl...","[[{'DataTableID': '7966', 'DataTableName': 'M9...",[]

In [ ]:
### Single phrase
df_singlephrase = ds.search_studies(search_text="younger dryas", limit=20)
df_singlephrase.head()

[2026-04-22 16:24:04,728][INFO] - search_studies: Limit set to 20.

[2026-04-22 16:24:04,728][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=20&searchText=younger+dryas

Parsing NOAA studies:   0%|                                                                           | 0/20 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 3191.04it/s]

[2026-04-22 16:24:05,788][WARNING] - Retrieved 20 studies, which is the specified limit. Consider increasing the limit parameter to fetch more studies.

[2026-04-22 16:24:05,790][INFO] - Retrieved 20 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,5898,2709,Aharon 2003 Gulf of Mexico Deglacial Stable Is...,PALEOCEANOGRAPHY,18000.0,1000.0,-16050.0,950.0,"(27.76, 27.76, -92.59, -92.59)",None,None,Paul Aharon,"[{'Author': 'Aharon, P.', 'Title': 'Meltwater ...","[[{'DataTableID': '33150', 'DataTableName': 'A...",[]
1,40939,82023,Alaskan Lake Stable Isotope and Geochemistry D...,PALEOLIMNOLOGY,15126.0,-68.0,-13176.0,2018.0,"(61.489946, 64.311005, -150.00032, -146.666764)","Provided Keywords: Paleohydrology, effective m...","[Pacific Decadal Oscillation, Atmospheric and ...","Lesleigh Anderson, Bruce Finney, W. Brad Baxter","[{'Author': 'Anderson, L., Finney, B.P., Baxte...","[[{'DataTableID': '55473', 'DataTableName': 'A...",[{'fundingAgency': 'United States Geological S...
2,25670,63714,Alkenone SST reconstructions from the eastern ...,PALEOCEANOGRAPHY,29840.0,790.0,-27890.0,1160.0,"(-3.38, -0.47, -89.68, -82.07)","Provided Keywords: Eastern Equatorial Pacific,...",[Sea Surface Temperature Reconstruction],"Athanasios Koutavas, Julian Sachs","[{'Author': 'Koutavas, A., and J.P. Sachs', 'T...","[[{'DataTableID': '37533', 'DataTableName': 'V...",[{'fundingAgency': 'US National Science Founda...
3,5919,2962,Andrews et al. 1999 Holocene High-Res Labrador...,PALEOCEANOGRAPHY,12000.0,0.0,-10050.0,1950.0,"(54.6165, 54.7952, -56.1766, -56.0583)",None,None,"Anne Jennings, John Andrews, Lloyd Keigwin, Fr...","[{'Author': 'Andrews, J. T., Keigwin, L., Hall...","[[{'DataTableID': '33128', 'DataTableName': 'A...",[]
4,11207,9643,Angola-Benguela Front ODP1078C 25KYr Alkenone ...,PALEOCEANOGRAPHY,24740.0,20.0,-22790.0,1930.0,"(-11.92, -11.92, 13.4, 13.4)",Alkenone sea-surface temperature (SST) estimat...,[Sea Surface Temperature Reconstruction],"Jung-Hyun Kim, Ralph Schneider, Stefan Mulitza...","[{'Author': 'Kim, J.-H., R.R. Schneider, S. Mu...","[[{'DataTableID': '19810', 'DataTableName': 'O...",[{'fundingAgency': 'Bundesministerium für Bild...

In [ ]:
### Logical operator (AND)
df_logop = ds.search_studies(search_text="loess AND stratigraphy", limit=20)
df_logop.head()

[2026-04-22 16:24:05,840][INFO] - search_studies: Limit set to 20.

[2026-04-22 16:24:05,840][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=20&searchText=loess+AND+stratigraphy

Parsing NOAA studies:   0%|                                                                            | 0/1 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]

[2026-04-22 16:24:06,334][INFO] - Retrieved 1 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,5599,2466,Ding et al. 1999 Lingtai Loess Stratigraphy Data,LOESS AND PALEOSOL,7000000,0,-6998050,1950,"(35.0667, 35.0667, 107.65, 107.65)",None,None,Zhongli Ding,"[{'Author': 'Ding, Z.L., S.F. Xiong, J.M. Sun,...","[[{'DataTableID': '32592', 'DataTableName': 'L...",[]

In [ ]:
### Wildcards: '_' (single char), '%' (multi-char)
df_wc_1 = ds.search_studies(search_text="f_re", limit=20)
df_wc_2 = ds.search_studies(search_text="pol%", limit=20)
df_wc_1.head(), df_wc_2.head()

[2026-04-22 16:24:06,366][INFO] - search_studies: Limit set to 20.

[2026-04-22 16:24:06,366][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=20&searchText=f_re

Parsing NOAA studies:   0%|                                                                           | 0/20 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 6533.69it/s]

[2026-04-22 16:24:07,233][WARNING] - Retrieved 20 studies, which is the specified limit. Consider increasing the limit parameter to fetch more studies.

[2026-04-22 16:24:07,233][INFO] - Retrieved 20 studies.

[2026-04-22 16:24:07,238][INFO] - search_studies: Limit set to 20.

[2026-04-22 16:24:07,238][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=20&searchText=pol%25

Parsing NOAA studies:   0%|                                                                           | 0/20 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|██████████████████████████████████████████████████████████████████████████| 20/20 [00:00<?, ?it/s]

[2026-04-22 16:24:08,354][WARNING] - Retrieved 20 studies, which is the specified limit. Consider increasing the limit parameter to fetch more studies.

[2026-04-22 16:24:08,354][INFO] - Retrieved 20 studies.

(  StudyID  XMLID                                          StudyName  \
 0    5473    652  A High-Resolution Record of Climatic Change in...
 1   18435  16119  Aishihik Basin, Yukon 12,000 Year Multiproxy L...
 2   22113  20095  Allen - Lake Riveaux/Abrotonella Rise - ATSE -...
 3    1926   5011  Anderson fire data from Swamp Lake - IMPD USSW...
 4   29752  71613  Andreu-Hayles - Ice Cut Dalton Highway - ALCR ...

          DataType  EarliestYearBP  MostRecentYearBP  EarliestYearCE  \
 0  PALEOLIMNOLOGY            1500               -32             450
 1  PALEOLIMNOLOGY           12906               -57          -10956
 2       TREE RING             538               -59            1412
 3    FIRE HISTORY           15819               -10          -13869
 4       TREE RING              30               -60            1920

    MostRecentYearCE                       Coverage [S, N, W, E]  \
 0              1982  (45.86694, 45.86694, -95.80361, -95.80361)
 1              2007    (61.2447, 61.2447, -136.9264, -136.9264)
 2              2009        (-43.183, -43.183, 146.595, 146.595)
 3              1960            (37.95, 37.95, -119.82, -119.82)
 4              2010                (69.0, 69.0, -148.8, -148.8)

                                           StudyNotes  \
 0  Geochemical and paleontological data sets for ...
 1  Multiproxy sediment data from Lake WA01, Aishi...
 2  Post-1930 disturbanes at this site, including ...
 3                                               None
 4  North Slope, Alaska, 2010 shrub ring-width dat...

                                      ScienceKeywords  \
 0                                               None
 1                                               None
 2  [ATSE, King Billy pine, Athrotaxis selaginoide...
 3                                               None
 4  [Alnus viridis var. crispa (Ait.) Turrill, Ame...

                                        Investigators  \
 0                        Roger Anderson, Walter Dean
 1                 Rebecca Rainville, Konrad Gajewski
 2                                      Kathryn Allen
 3                                  R. Scott Anderson
 4  Laia Andreu-Hayles, Kevin Anchukaitis, Javi Ma...

                                         Publications  \
 0  [{'Author': 'Walter E. Dean, J.P. Bradbury, R....
 1  [{'Author': 'Rebecca A. Rainville and Konrad G...
 2  [{'Author': 'K.J. Allen,  J. Ogden, B.M. Buckl...
 3                                                 []
 4  [{'Author': 'Laia Andreu-Hayles, Benjamin V. G...

                                                Sites  \
 0  [[{'DataTableID': '8031', 'DataTableName': 'El...
 1  [[{'DataTableID': '28800', 'DataTableName': 'W...
 2  [[{'DataTableID': '33245', 'DataTableName': 'A...
 3  [[{'DataTableID': '2062', 'DataTableName': 'US...
 4  [[{'DataTableID': '42277', 'DataTableName': 'A...

                                              Funding
 0                                                 []
 1  [{'fundingAgency': 'Natural Sciences and Engin...
 2  [{'fundingAgency': 'Australian Research Counci...
 3                                                 []
 4  [{'fundingAgency': 'US National Science Founda...  ,
   StudyID  XMLID                                          StudyName  \
 0   10437   9101  1,000 Year Ensemble Reconstructions of Tempera...
 1   36253  77512  10Be Chronology of Khoton Nuur Glacial Landfor...
 2   22315  20388        2000 Year Tropical Rainfall Reconstructions
 3   12894  10958  9400 Year Cosmogenic Isotope Data and Solar Ac...
 4   19281  16968  A global planktic foraminifer census data set ...

                   DataType  EarliestYearBP  MostRecentYearBP  EarliestYearCE  \
 0  CLIMATE RECONSTRUCTIONS           950.0             -45.0          1000.0
 1  CLIMATE RECONSTRUCTIONS         35000.0           16000.0        -33050.0
 2  CLIMATE RECONSTRUCTIONS          2000.0             -50.0           -50.0
 3          CLIMATE FORCING          9389.0             -27.0         -7439.0
 4         PALEOCEANOGRAPHY       6181000.0         1603000.0      -6179050.0

    MostRecentYearCE                        Coverage [S, N, W, E]  \
 0            1995.0                   (0.0, 90.0, -180.0, 180.0)
 1          -14050.0  (48.613232, 48.97233, 88.078977, 88.430928)
 2            2000.0                 (-30.0, 30.0, -180.0, 180.0)
 3            1977.0                 (-90.0, 90.0, -180.0, 180.0)
 4        -1601050.0                         (nan, nan, nan, nan)

                                           StudyNotes  \
 0  Calibration ensemble reconstructions of existi...
 1                                               None
 2  Composite reconstruction of low latitude rainf...
 3  Records of common production rate of cosmogeni...
 4  Data Compilers: Foley, Kevin; Robinson, Marci;...

                                      ScienceKeywords  \
 0  [carbon cycle, sensitivity, Air Temperature Re...
 1                                               None
 2                     [Precipitation Reconstruction]
 3                     [Solar Forcing Reconstruction]
 4                                               None

                                        Investigators  \
 0  David Frank, Jan Esper, Christoph Raible, Ulf ...
 1  Peter Strand, Aaron Putnam, Oyungerel Sambuu, ...
 2  Franziska Lechleitner, Sebastian Breitenbach, ...
 3  Friedhelm Steinhilber, Jose Abreu, Jürg Beer, ...
 4  Kevin Foley, Marci Robinson, Harry Dowsett, Ri...

                                         Publications  \
 0  [{'Author': 'Frank, D.C., J. Esper, C.C. Raibl...
 1  [{'Author': 'Strand, Peter D., Aaron E. Putnam...
 2  [{'Author': 'Franziska A. Lechleitner, Sebasti...
 3  [{'Author': 'Steinhilber, F., J.A. Abreu, J. B...
 4  [{'Author': 'Dowsett, H., M. Robinson, A. Hayw...

                                                Sites  \
 0  [[{'DataTableID': '19235', 'DataTableName': 'F...
 1  [[{'DataTableID': '48957', 'DataTableName': 'K...
 2  [[{'DataTableID': '33444', 'DataTableName': 'L...
 3  [[{'DataTableID': '21230', 'DataTableName': 'T...
 4  [[{'DataTableID': '1002175', 'DataTableName': ...

                                              Funding
 0  [{'fundingAgency': 'Swiss National Science Fou...
 1  [{'fundingAgency': 'US National Science Founda...
 2  [{'fundingAgency': 'European Union', 'fundingG...
 3  [{'fundingAgency': 'Swiss National Science Fou...
 4                                                 []  )

In [ ]:
### Escaping special characters (use backslashes)
df_specchar = ds.search_studies(search_text=r"noaa\-tree\-19260", limit=20)
df_specchar.head()

[2026-04-22 16:24:08,412][INFO] - search_studies: Limit set to 20.

[2026-04-22 16:24:08,412][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=20&searchText=noaa%5C-tree%5C-19260

Parsing NOAA studies:   0%|                                                                            | 0/1 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]

[2026-04-22 16:24:09,012][INFO] - Retrieved 1 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,19260,16927,Samonil - Zofinsky prales - ABAL - ITRDB CZEC003,TREE RING,363,-60,1587,2010,"(48.6667, 48.6667, 14.7, 14.7)",NOAA Template Chronology file added 2018-12-1...,"[Abies alba Mill., European silver fir, ABAL, ...","Pavel Šamonil, Petra Doleželová, Ivana Vašíčko...","[{'Author': 'Pavel Šamonil, Petra Doleželová, ...","[[{'DataTableID': '29759', 'DataTableName': 'C...",[]

In [ ]:
### Multiple investigators (OR by default)
df_multinv_default = ds.search_studies(investigators=["Wahl, E.R.", "Vose, R.S."])
df_multinv_default.head()

[2026-04-22 16:24:09,046][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:09,046][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=100&investigators=Wahl%2C+E.R.%7CVose%2C+R.S.&investigatorsAndOr=or

Parsing NOAA studies:   0%|                                                                           | 0/24 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 3546.98it/s]

[2026-04-22 16:24:10,164][INFO] - Retrieved 24 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,8405,2665,Ammann and Wahl 2007 N. Hemisphere Temperature...,CLIMATE RECONSTRUCTIONS,950,-30,1000,1980,"(0.0, 80.0, -180.0, 180.0)",Northern hemisphere multiproxy average annual ...,[Air Temperature Reconstruction],"Caspar Ammann, Eugene Wahl","[{'Author': 'Ammann, C.M. and E.R. Wahl', 'Tit...","[[{'DataTableID': '19446', 'DataTableName': 'P...",[{'fundingAgency': 'US National Center for Atm...
1,18295,15997,California and Western Nevada Precipitation Re...,CLIMATE RECONSTRUCTIONS,379,-27,1571,1977,"(32.5, 42.0, -124.4, -116.5)",Water year (October through following Septembe...,"[Precipitation Reconstruction, drought]","Henry Diaz, Eugene Wahl",[{'Author': 'Henry F. Diaz and Eugene R. Wahl'...,"[[{'DataTableID': '28654', 'DataTableName': 'C...",[]
2,19600,17329,European Mean and Spatial Summer Temperature R...,CLIMATE RECONSTRUCTIONS,2088,-53,-138,2003,"(35.0, 70.0, -25.0, 40.0)",Spatial (5x5 degree grid) reconstructions of E...,"[PAGES Euro-Med 2k, Air Temperature Reconstruc...","Jürg Luterbacher, Johannes Werner, Jason Smerd...","[{'Author': 'J. Luterbacher, J. P. Werner, J. ...","[[{'DataTableID': '30218', 'DataTableName': 'L...",[{'fundingAgency': 'US National Science Founda...
3,20465,18279,Hawaiian Islands 500 Year Winter Rainfall and ...,CLIMATE RECONSTRUCTIONS,450,-62,1500,2012,"(18.72, 23.95, -166.74, -156.15)",Reconstructions of Hawaii winter (Dec-Feb) pre...,"[Precipitation Reconstruction, Other Reconstru...","Henry Diaz, Eugene Wahl, Eduardo Zorita, Thoma...","[{'Author': 'Henry F. Diaz, Eugene R. Wahl, Ed...","[[{'DataTableID': '31159', 'DataTableName': 'H...",[]
4,22454,20650,Living Blended Drought Atlas (LBDA) Version 2 ...,CLIMATE RECONSTRUCTIONS,1950,-75,0,2025,"(24.0, 50.0, -124.0, -68.0)",The half-degree gridded June-August Palmer Mod...,"[drought, Palmer Drought Index Reconstruction]","Edward Gille, Carrie Morrill, Eugene Wahl, Rus...","[{'Author': 'Cook, E.R., Seager, R., Heim, R.R...","[[{'DataTableID': '33588', 'DataTableName': 'C...",[{'fundingAgency': 'US National Oceanic and At...

In [ ]:
### Multiple investigators (AND by default)
df_multinv_and = ds.search_studies(investigators=["Wahl, E.R.", "Vose, R.S."], investigatorsAndOr = "and")
df_multinv_and.head()

[2026-04-22 16:24:10,221][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:10,223][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=100&investigators=Wahl%2C+E.R.%7CVose%2C+R.S.&investigatorsAndOr=or

Parsing NOAA studies:   0%|                                                                           | 0/24 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 3904.86it/s]

[2026-04-22 16:24:11,341][INFO] - Retrieved 24 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,8405,2665,Ammann and Wahl 2007 N. Hemisphere Temperature...,CLIMATE RECONSTRUCTIONS,950,-30,1000,1980,"(0.0, 80.0, -180.0, 180.0)",Northern hemisphere multiproxy average annual ...,[Air Temperature Reconstruction],"Caspar Ammann, Eugene Wahl","[{'Author': 'Ammann, C.M. and E.R. Wahl', 'Tit...","[[{'DataTableID': '19446', 'DataTableName': 'P...",[{'fundingAgency': 'US National Center for Atm...
1,18295,15997,California and Western Nevada Precipitation Re...,CLIMATE RECONSTRUCTIONS,379,-27,1571,1977,"(32.5, 42.0, -124.4, -116.5)",Water year (October through following Septembe...,"[Precipitation Reconstruction, drought]","Henry Diaz, Eugene Wahl",[{'Author': 'Henry F. Diaz and Eugene R. Wahl'...,"[[{'DataTableID': '28654', 'DataTableName': 'C...",[]
2,19600,17329,European Mean and Spatial Summer Temperature R...,CLIMATE RECONSTRUCTIONS,2088,-53,-138,2003,"(35.0, 70.0, -25.0, 40.0)",Spatial (5x5 degree grid) reconstructions of E...,"[PAGES Euro-Med 2k, Air Temperature Reconstruc...","Jürg Luterbacher, Johannes Werner, Jason Smerd...","[{'Author': 'J. Luterbacher, J. P. Werner, J. ...","[[{'DataTableID': '30218', 'DataTableName': 'L...",[{'fundingAgency': 'US National Science Founda...
3,20465,18279,Hawaiian Islands 500 Year Winter Rainfall and ...,CLIMATE RECONSTRUCTIONS,450,-62,1500,2012,"(18.72, 23.95, -166.74, -156.15)",Reconstructions of Hawaii winter (Dec-Feb) pre...,"[Precipitation Reconstruction, Other Reconstru...","Henry Diaz, Eugene Wahl, Eduardo Zorita, Thoma...","[{'Author': 'Henry F. Diaz, Eugene R. Wahl, Ed...","[[{'DataTableID': '31159', 'DataTableName': 'H...",[]
4,22454,20650,Living Blended Drought Atlas (LBDA) Version 2 ...,CLIMATE RECONSTRUCTIONS,1950,-75,0,2025,"(24.0, 50.0, -124.0, -68.0)",The half-degree gridded June-August Palmer Mod...,"[drought, Palmer Drought Index Reconstruction]","Edward Gille, Carrie Morrill, Eugene Wahl, Rus...","[{'Author': 'Cook, E.R., Seager, R., Heim, R.R...","[[{'DataTableID': '33588', 'DataTableName': 'C...",[{'fundingAgency': 'US National Oceanic and At...

In [ ]:
### Keywords: hierarchy with '>' and multiple via '|'
df_keywords = ds.search_studies(keywords="earth science>paleoclimate>paleocean>biomarkers")
df_keywords.head()

[2026-04-22 16:24:11,398][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:11,399][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=100&keywords=earth+science%3Epaleoclimate%3Epaleocean%3Ebiomarkers

Parsing NOAA studies:   0%|                                                                          | 0/100 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|██████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 4147.68it/s]

[2026-04-22 16:24:12,986][INFO] - Retrieved 100 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,22588,20773,2.8 million years of alkenone and TEX86 data a...,PALEOCEANOGRAPHY,2785481.0,257.0,-2783531.0,1693.0,"(18.836, 18.836, 116.566, 116.566)",Surface and subsurface temperature difference ...,[Sea Surface Temperature Reconstruction],"Dawei Li, Meixun Zhao, Jun Tian","[{'Author': 'Li, D., M. Zhao, and J. Tian', 'T...","[[{'DataTableID': '33711', 'DataTableName': 'O...",[]
1,34232,75912,"Adélie Drift, East Antarctic Fatty Acid Carbon...",PALEOCEANOGRAPHY,363.0,-48.0,1587.0,1998.0,"(-66.408333, -66.408333, 140.4405, 140.4405)","Provided Keywords: Paleoceanography, Sea Ice R...",None,"Kate Ashley, James Bendle, Xavier Crosta, Joha...","[{'Author': 'Ashley, Kate, James Bendle, Xavie...","[[{'DataTableID': '47058', 'DataTableName': 'D...",[{'fundingAgency': 'European Commission Sevent...
2,33472,75092,Agulhas Plateau Biomarker Data and SST Reconst...,PALEOCEANOGRAPHY,1400000.0,339800.0,-1398050.0,-337850.0,"(-41.2561, -41.2561, 25.1564, 25.1564)",A new biomarker records of upper water column ...,[Sea Surface Temperature Reconstruction],"Alejandra Cartagena-Sierra, Melissa Berke, Reb...","[{'Author': 'Cartagena-Sierra, A., Berke, M.A....","[[{'DataTableID': '46117', 'DataTableName': 'I...",[{'fundingAgency': 'US National Science Founda...
3,25670,63714,Alkenone SST reconstructions from the eastern ...,PALEOCEANOGRAPHY,29840.0,790.0,-27890.0,1160.0,"(-3.38, -0.47, -89.68, -82.07)","Provided Keywords: Eastern Equatorial Pacific,...",[Sea Surface Temperature Reconstruction],"Athanasios Koutavas, Julian Sachs","[{'Author': 'Koutavas, A., and J.P. Sachs', 'T...","[[{'DataTableID': '37533', 'DataTableName': 'V...",[{'fundingAgency': 'US National Science Founda...
4,22400,20534,"Alkenone paleotemperature estimates, d18O seaw...",PALEOCEANOGRAPHY,18170.0,400.0,-16220.0,1550.0,"(56.96, 57.872382, -137.10446, -136.43)",Source reference for EW0408-66JC and EW0408-26...,[Sea Surface Temperature Reconstruction],"Summer Praetorius, Alan Mix, Britta Jensen, Du...","[{'Author': 'Praetorius, S.K, A.C. Mix, B. Jen...","[[{'DataTableID': '33517', 'DataTableName': 'E...",[{'fundingAgency': 'US National Science Founda...

In [ ]:
### Location hierarchy
df_loc = ds.search_studies(locations="Continent>Africa>Eastern Africa>Zambia")
df_loc.head()

[2026-04-22 16:24:13,069][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:13,070][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=100&locations=Continent%3EAfrica%3EEastern+Africa%3EZambia

Parsing NOAA studies:   0%|                                                                           | 0/24 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 1520.46it/s]

[2026-04-22 16:24:15,093][INFO] - Retrieved 24 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,1000537,1000160,Global Database of Borehole Temperatures and C...,BOREHOLE,450,-22,1500,1972,"(-13.92, -13.92, 29.2, 29.2)","This project has as its goal the design, asse...","[Air Temperature Reconstruction, temperature]","Shaopeng Huang, Henry Pollack, Po Yu Shen","[{'Author': 'Huang, S., Pollack, H.N., and She...","[[{'DataTableID': '1000631', 'DataTableName': ...",[{'fundingAgency': 'US National Science Founda...
1,1000538,1000161,Global Database of Borehole Temperatures and C...,BOREHOLE,450,-22,1500,1972,"(-13.92, -13.92, 29.2, 29.2)","This project has as its goal the design, asse...","[Air Temperature Reconstruction, temperature]","Shaopeng Huang, Henry Pollack, Po Yu Shen","[{'Author': 'Huang, S., Pollack, H.N., and She...","[[{'DataTableID': '1000632', 'DataTableName': ...",[{'fundingAgency': 'US National Science Founda...
2,1000540,1000163,Global Database of Borehole Temperatures and C...,BOREHOLE,450,-24,1500,1974,"(-15.82, -15.82, 27.92, 27.92)","This project has as its goal the design, asse...","[temperature, Air Temperature Reconstruction]","Shaopeng Huang, Henry Pollack, Po Yu Shen","[{'Author': 'Huang, S., Pollack, H.N., and She...","[[{'DataTableID': '1000634', 'DataTableName': ...",[{'fundingAgency': 'US National Science Founda...
3,1000541,1000164,Global Database of Borehole Temperatures and C...,BOREHOLE,450,-24,1500,1974,"(-13.08, -13.08, 28.05, 28.05)","This project has as its goal the design, asse...","[temperature, Air Temperature Reconstruction]","Shaopeng Huang, Henry Pollack, Po Yu Shen","[{'Author': 'Huang, S., Pollack, H.N., and She...","[[{'DataTableID': '1000635', 'DataTableName': ...",[{'fundingAgency': 'US National Science Founda...
4,1000539,1000162,Global Database of Borehole Temperatures and C...,BOREHOLE,450,-38,1500,1988,"(-12.58, -12.58, 31.65, 31.65)","This project has as its goal the design, asse...","[temperature, Air Temperature Reconstruction]","Shaopeng Huang, Henry Pollack, Po Yu Shen","[{'Author': 'Huang, S., Pollack, H.N., and She...","[[{'DataTableID': '1000633', 'DataTableName': ...",[{'fundingAgency': 'US National Science Founda...

In [ ]:
### Species: four-letter codes (uppercase enforced)
df_species = ds.search_studies(species=["ABAL", "PIPO"])
df_species.head()

[2026-04-22 16:24:15,142][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:15,142][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=100&species=ABAL%7CPIPO&speciesAndOr=or

Parsing NOAA studies:   0%|                                                                          | 0/100 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|██████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 6819.12it/s]

[2026-04-22 16:24:16,895][INFO] - Retrieved 100 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,26070,64380,Azpeleta Tarancón fire data from Mistletoe Can...,FIRE HISTORY,418,-64,1532,2014,"(33.215925, 33.215925, -105.608842, -105.608842)",This site was sampled to assess the spatiotemp...,"[PIST, eastern white pine, Pseudotsuga menzies...","Alicia Azpeleta Tarancón, Peter Fulé, Andrew S...","[{'Author': 'Azpeleta Tarancon, A., Fulé, P.Z....","[[{'DataTableID': '37993', 'DataTableName': 'U...",[{'fundingAgency': 'US Department of Agricultu...
1,26071,64375,Azpeleta Tarancón fire data from Potato Patch ...,FIRE HISTORY,271,-65,1679,2015,"(33.043863, 33.043863, -105.724789, -105.724789)",This site was sampled to assess the spatiotemp...,"[eastern white pine, Pinus ponderosa Douglas e...","Alicia Azpeleta Tarancón, Peter Fulé, Andrew S...","[{'Author': 'Azpeleta Tarancon, A., Fulé, P.Z....","[[{'DataTableID': '37994', 'DataTableName': 'U...",[{'fundingAgency': 'USDA National Institute of...
2,26073,64376,"Azpeleta Tarancón fire data from Snow Canyon, ...",FIRE HISTORY,578,-14,1372,1964,"(33.240746, 33.240746, -105.638039, -105.638039)",This site was sampled to assess the spatiotemp...,"[eastern white pine, Pseudotsuga menziesii (Mi...","Alicia Azpeleta Tarancón, Peter Fulé, Andrew S...","[{'Author': 'Azpeleta Tarancon, A., Fulé, P.Z....","[[{'DataTableID': '37996', 'DataTableName': 'U...",[]
3,26072,64374,"Azpeleta Tarancón fire data from Solon, south ...",FIRE HISTORY,351,-62,1599,2012,"(33.051347, 33.051347, -105.556574, -105.556574)","Tarancón fire data from Solon, south central N...","[eastern white pine, Pinus ponderosa Douglas e...","Alicia Azpeleta Tarancón, Peter Fulé, Andrew S...","[{'Author': 'Azpeleta Tarancon, A., Fulé, P.Z....","[[{'DataTableID': '37995', 'DataTableName': 'U...",[{'fundingAgency': 'USDA National Institute of...
4,26074,64381,Azpeleta Tarancón fire data from Turkey Canyon...,FIRE HISTORY,343,-53,1607,2003,"(33.099762, 33.099762, -105.549527, -105.549527)",This site was sampled to assess the spatiotemp...,"[ponderosa pine, PIPO, western yellow pine, Pi...","Alicia Azpeleta Tarancón, Peter Fulé, Andrew S...","[{'Author': 'Azpeleta Tarancon, A., Fulé, P.Z....","[[{'DataTableID': '37997', 'DataTableName': 'U...",[{'fundingAgency': 'USDA National Institute of...

In [ ]:
### Data types: one or more IDs separated by '|'
df_muldatatypes = ds.search_studies(data_type_id="4|18")
df_muldatatypes.head()

[2026-04-22 16:24:16,931][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:16,931][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataTypeID=4%7C18&dataPublisher=NOAA&limit=100

Parsing NOAA studies:   0%|                                                                          | 0/100 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|██████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1548.31it/s]

[2026-04-22 16:24:18,341][INFO] - Retrieved 100 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,10437,9101,"1,000 Year Ensemble Reconstructions of Tempera...",CLIMATE RECONSTRUCTIONS,950.0,-45.0,1000.0,1995.0,"(0.0, 90.0, -180.0, 180.0)",Calibration ensemble reconstructions of existi...,"[carbon cycle, sensitivity, Air Temperature Re...","David Frank, Jan Esper, Christoph Raible, Ulf ...","[{'Author': 'Frank, D.C., J. Esper, C.C. Raibl...","[[{'DataTableID': '19235', 'DataTableName': 'F...",[{'fundingAgency': 'Swiss National Science Fou...
1,11194,9632,"1,100 Year El Niño/Southern Oscillation (ENSO)...",CLIMATE RECONSTRUCTIONS,1050.0,-52.0,900.0,2002.0,"(-20.0, 20.0, 145.0, -80.0)",An index of canonical ENSO variability for the...,"[ENSO, Atmospheric and Oceanic Circulation Pat...","Jinbao Li, Shang-Ping Xie, Edward Cook, Gang H...","[{'Author': 'Li, J., S.-P. Xie, E.R. Cook, G. ...","[[{'DataTableID': '19791', 'DataTableName': 'e...",[{'fundingAgency': 'US National Science Founda...
2,14193,12194,1000 Year Composite Sea Surface Temperature Re...,PALEOCEANOGRAPHY,950.0,-46.0,1000.0,1996.0,"(56.66667, 69.48333, -18.1957, 18.36667)",A set of reconstructions of sea surface temper...,None,"Laura Cunningham, William Austin, Karen-Luise ...","[{'Author': 'Cunningham, L.K., Austin, W.E.N.,...","[[{'DataTableID': '24146', 'DataTableName': 'P...","[{'fundingAgency': 'European Commission', 'fun..."
3,42679,83754,1006-year reconstruction of Rossby wavenumber-5,CLIMATE RECONSTRUCTIONS,950.0,-55.0,1000.0,2005.0,"(0.0, 90.0, -180.0, 180.0)",None,[Atmospheric and Oceanic Circulation Patterns ...,"Ellie Broadman, Valerie Trouet, Kai Kornhuber","[{'Author': 'Broadman, Ellie, Kai Kornhuber, I...","[[{'DataTableID': '56946', 'DataTableName': 'W...",[{'fundingAgency': 'US National Science Founda...
4,36253,77512,10Be Chronology of Khoton Nuur Glacial Landfor...,CLIMATE RECONSTRUCTIONS,35000.0,16000.0,-33050.0,-14050.0,"(48.613232, 48.97233, 88.078977, 88.430928)",None,None,"Peter Strand, Aaron Putnam, Oyungerel Sambuu, ...","[{'Author': 'Strand, Peter D., Aaron E. Putnam...","[[{'DataTableID': '48957', 'DataTableName': 'K...",[{'fundingAgency': 'US National Science Founda...

In [ ]:
df_latlong = ds.search_studies(min_lat=68, max_lat=69, min_lon=30, max_lon=40)
df_latlong.head()

[2026-04-22 16:24:18,396][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:18,397][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=100&minLat=68&maxLat=69&minLon=30&maxLon=40

Parsing NOAA studies:   0%|                                                                          | 0/100 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|██████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 9045.30it/s]

[2026-04-22 16:24:19,659][INFO] - Retrieved 100 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,10437,9101,"1,000 Year Ensemble Reconstructions of Tempera...",CLIMATE RECONSTRUCTIONS,950.0,-45.0,1000.0,1995.0,"(0.0, 90.0, -180.0, 180.0)",Calibration ensemble reconstructions of existi...,"[carbon cycle, sensitivity, Air Temperature Re...","David Frank, Jan Esper, Christoph Raible, Ulf ...","[{'Author': 'Frank, D.C., J. Esper, C.C. Raibl...","[[{'DataTableID': '19235', 'DataTableName': 'F...",[{'fundingAgency': 'Swiss National Science Fou...
1,42679,83754,1006-year reconstruction of Rossby wavenumber-5,CLIMATE RECONSTRUCTIONS,950.0,-55.0,1000.0,2005.0,"(0.0, 90.0, -180.0, 180.0)",None,[Atmospheric and Oceanic Circulation Patterns ...,"Ellie Broadman, Valerie Trouet, Kai Kornhuber","[{'Author': 'Broadman, Ellie, Kai Kornhuber, I...","[[{'DataTableID': '56946', 'DataTableName': 'W...",[{'fundingAgency': 'US National Science Founda...
2,12203,10267,2000 Year Precipitation-Based Southern Oscilla...,CLIMATE RECONSTRUCTIONS,1900.0,-5.0,50.0,1955.0,"(-90.0, 90.0, -180.0, 180.0)",Reconstruction of a precipitation-based Southe...,[Atmospheric and Oceanic Circulation Patterns ...,"Hong Yan, Liguang Sun, Yuhong Wang, Wen Huang,...","[{'Author': 'Yan, H., L. Sun, Y. Wang, W. Huan...","[[{'DataTableID': '20526', 'DataTableName': 'S...",[{'fundingAgency': 'National Natural Science F...
3,14190,12191,600 Year Ensemble Climate Reconstructions and ...,CLIMATE RECONSTRUCTIONS,550.0,-61.0,1400.0,2011.0,"(45.0, 85.0, -180.0, 180.0)","Ensemble Climate Reconstructions, input data f...",[Air Temperature Reconstruction],"Martin Tingley, Peter Huybers","[{'Author': 'Tingley, M.P. and P. Huybers', 'T...","[[{'DataTableID': '24136', 'DataTableName': 'T...",[{'fundingAgency': 'US National Science Founda...
4,12894,10958,9400 Year Cosmogenic Isotope Data and Solar Ac...,CLIMATE FORCING,9389.0,-27.0,-7439.0,1977.0,"(-90.0, 90.0, -180.0, 180.0)",Records of common production rate of cosmogeni...,[Solar Forcing Reconstruction],"Friedhelm Steinhilber, Jose Abreu, Jürg Beer, ...","[{'Author': 'Steinhilber, F., J.A. Abreu, J. B...","[[{'DataTableID': '21230', 'DataTableName': 'T...",[{'fundingAgency': 'Swiss National Science Fou...

In [ ]:
df_elv = ds.search_studies(min_elevation=100, max_elevation=110)
df_elv.head()

[2026-04-22 16:24:19,702][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:19,704][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=100&minElev=100&maxElev=110

Parsing NOAA studies:   0%|                                                                          | 0/100 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|██████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 7691.74it/s]

[2026-04-22 16:24:21,052][INFO] - Retrieved 100 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,40170,81293,"Abissal Cave, Rainha Cave Geochemical Data fro...",SPELEOTHEMS,25694.0,4044.0,-23744.0,-2094.0,"(-5.5782, -5.5642, -37.6659, -37.6432)",Data contributed as part of SISAL v3 Global Sp...,None,"Francisco Cruz, Mathias Vuille, Stephen Burns,...","[{'Author': 'Cruz, Francisco W.; Mathias Vuill...","[[{'DataTableID': '53529', 'DataTableName': 'A...",[]
1,40477,81622,Adenesky-Filho - Blumenau - SC - CEFI - ITRDB ...,TREE RING,13.0,-61.0,1937.0,2011.0,"(-26.904761, -26.904761, -49.114204, -49.114204)",Tropical Tree Ring Network SiteID = CEFIS_BRA_07,"[CEFI, Cedrela fissilis Vell., Cedro rosa]","Eduardo Adenesky-Filho, Karin Esemann-Quadros,...","[{'Author': 'Unknown Author', 'Title': 'Unknow...","[[{'DataTableID': '54044', 'DataTableName': 'B...",[]
2,40939,82023,Alaskan Lake Stable Isotope and Geochemistry D...,PALEOLIMNOLOGY,15126.0,-68.0,-13176.0,2018.0,"(61.489946, 64.311005, -150.00032, -146.666764)","Provided Keywords: Paleohydrology, effective m...","[Pacific Decadal Oscillation, Atmospheric and ...","Lesleigh Anderson, Bruce Finney, W. Brad Baxter","[{'Author': 'Anderson, L., Finney, B.P., Baxte...","[[{'DataTableID': '55473', 'DataTableName': 'A...",[{'fundingAgency': 'United States Geological S...
3,31418,73106,Allen - Tiwi Islands - CAIN - ITRDB AUSL060,TREE RING,73.0,-57.0,1877.0,2007.0,"(-11.71, -11.71, 130.83, 130.83)",Callitris intratropica ring-width data used fo...,"[CAIN, cypress pine, Callitris intratropica R....","Kathryn Allen, Jonathan Palmer, Patrick Baker","[{'Author': 'K.J. Allen, M.B. Freund, J.G. Pal...","[[{'DataTableID': '43922', 'DataTableName': 'A...",[{'fundingAgency': 'Australian Research Counci...
4,28315,68766,Arnold - Codnor Castle - QUSP - ITRDB BRIT078,TREE RING,569.0,391.0,1381.0,1559.0,"(53.044355, 53.044355, -1.354599, -1.354599)",NOAA Template Raw Measurements file added 2020...,"[Quercus spp. L., oak, QUSP]","Alison Arnold, Robert Howard",[],"[[{'DataTableID': '40602', 'DataTableName': 'B...","[{'fundingAgency': 'Historic England', 'fundin..."

In [ ]:
### Explicit BP with method
df_timew = ds.search_studies(earliest_year=12000, time_format="BP", time_method="overAny")
df_timew.head()

[2026-04-22 16:24:21,103][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:21,104][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=100&earliestYear=12000&timeFormat=BP&timeMethod=overAny

Parsing NOAA studies:   0%|                                                                          | 0/100 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|██████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 4019.61it/s]

[2026-04-22 16:24:22,538][INFO] - Retrieved 100 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,10437,9101,"1,000 Year Ensemble Reconstructions of Tempera...",CLIMATE RECONSTRUCTIONS,950,-45,1000,1995,"(0.0, 90.0, -180.0, 180.0)",Calibration ensemble reconstructions of existi...,"[carbon cycle, sensitivity, Air Temperature Re...","David Frank, Jan Esper, Christoph Raible, Ulf ...","[{'Author': 'Frank, D.C., J. Esper, C.C. Raibl...","[[{'DataTableID': '19235', 'DataTableName': 'F...",[{'fundingAgency': 'Swiss National Science Fou...
1,11194,9632,"1,100 Year El Niño/Southern Oscillation (ENSO)...",CLIMATE RECONSTRUCTIONS,1050,-52,900,2002,"(-20.0, 20.0, 145.0, -80.0)",An index of canonical ENSO variability for the...,"[ENSO, Atmospheric and Oceanic Circulation Pat...","Jinbao Li, Shang-Ping Xie, Edward Cook, Gang H...","[{'Author': 'Li, J., S.-P. Xie, E.R. Cook, G. ...","[[{'DataTableID': '19791', 'DataTableName': 'e...",[{'fundingAgency': 'US National Science Founda...
2,14193,12194,1000 Year Composite Sea Surface Temperature Re...,PALEOCEANOGRAPHY,950,-46,1000,1996,"(56.66667, 69.48333, -18.1957, 18.36667)",A set of reconstructions of sea surface temper...,None,"Laura Cunningham, William Austin, Karen-Luise ...","[{'Author': 'Cunningham, L.K., Austin, W.E.N.,...","[[{'DataTableID': '24146', 'DataTableName': 'P...","[{'fundingAgency': 'European Commission', 'fun..."
3,42679,83754,1006-year reconstruction of Rossby wavenumber-5,CLIMATE RECONSTRUCTIONS,950,-55,1000,2005,"(0.0, 90.0, -180.0, 180.0)",None,[Atmospheric and Oceanic Circulation Patterns ...,"Ellie Broadman, Valerie Trouet, Kai Kornhuber","[{'Author': 'Broadman, Ellie, Kai Kornhuber, I...","[[{'DataTableID': '56946', 'DataTableName': 'W...",[{'fundingAgency': 'US National Science Founda...
4,22031,20009,1200 Year Atlantic Multidecadal Variability an...,CLIMATE RECONSTRUCTIONS,1150,-60,800,2010,"(0.0, 70.0, -80.0, 0.0)",Summer (May-September) Atlantic Multidecadal V...,[Atmospheric and Oceanic Circulation Patterns ...,"Jianglin Wang, Bao Yang, Fredrik Ljungqvist, J...","[{'Author': 'Jianglin Wang, Bao Yang, Fredrik ...","[[{'DataTableID': '33108', 'DataTableName': 'W...",[{'fundingAgency': 'National Natural Science F...

In [ ]:
### No time_format/time_method → defaults to CE
df_time_defualt = ds.search_studies(earliest_year=1500, latest_year=0)
df_time_defualt.head()

[2026-04-22 16:24:22,659][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:22,660][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

[2026-04-22 16:24:22,661][INFO] - search_studies: time_format not provided; defaulted to 'CE'.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=100&earliestYear=1500&latestYear=0&timeFormat=CE

Parsing NOAA studies:   0%|                                                                          | 0/100 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|██████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 4076.73it/s]

[2026-04-22 16:24:24,468][INFO] - Retrieved 100 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,22588,20773,2.8 million years of alkenone and TEX86 data a...,PALEOCEANOGRAPHY,2785481,257,-2783531,1693,"(18.836, 18.836, 116.566, 116.566)",Surface and subsurface temperature difference ...,[Sea Surface Temperature Reconstruction],"Dawei Li, Meixun Zhao, Jun Tian","[{'Author': 'Li, D., M. Zhao, and J. Tian', 'T...","[[{'DataTableID': '33711', 'DataTableName': 'O...",[]
1,22315,20388,2000 Year Tropical Rainfall Reconstructions,CLIMATE RECONSTRUCTIONS,2000,-50,-50,2000,"(-30.0, 30.0, -180.0, 180.0)",Composite reconstruction of low latitude rainf...,[Precipitation Reconstruction],"Franziska Lechleitner, Sebastian Breitenbach, ...","[{'Author': 'Franziska A. Lechleitner, Sebasti...","[[{'DataTableID': '33444', 'DataTableName': 'L...","[{'fundingAgency': 'European Union', 'fundingG..."
2,22390,20667,"860,000 Years of foraminifera-bound nitrogen i...",PALEOCEANOGRAPHY,860000,0,-858050,1950,"(12.68, 12.68, 119.45, 119.45)","A 860,000-year nitrogen isotope record from So...",None,"Haojia Ren, Daniel Sigman, Alfredo Martínez-Ga...","[{'Author': 'Ren, H.; Sigman, D.M.; Martinez-G...","[[{'DataTableID': '33610', 'DataTableName': 'M...",[]
3,12894,10958,9400 Year Cosmogenic Isotope Data and Solar Ac...,CLIMATE FORCING,9389,-27,-7439,1977,"(-90.0, 90.0, -180.0, 180.0)",Records of common production rate of cosmogeni...,[Solar Forcing Reconstruction],"Friedhelm Steinhilber, Jose Abreu, Jürg Beer, ...","[{'Author': 'Steinhilber, F., J.A. Abreu, J. B...","[[{'DataTableID': '21230', 'DataTableName': 'T...",[{'fundingAgency': 'Swiss National Science Fou...
4,15090,12950,A 2000 year long seasonal record of floods in ...,PALEOLIMNOLOGY,2067,-48,-117,1998,"(45.876667, 45.876667, 10.750556, 10.750556)",This dataset contains ages and thicknesses of ...,"[Seasonal Resolution (SR), Little Ice Age (LIA...","Stefanie Wirth, Adrian Gilli, Anaëlle Simonnea...","[{'Author': 'Wirth, S. B., A. Gilli, A. Simonn...","[[{'DataTableID': '25120', 'DataTableName': 'T...",[{'fundingAgency': 'Swiss National Science Fou...

In [ ]:
df_recon = ds.search_studies(reconstruction=True)
df_recon.head()

[2026-04-22 16:24:24,515][INFO] - search_studies: Limit defaulted to 100 (PyleoTUPS).

[2026-04-22 16:24:24,515][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=100&reconstructionsOnly=Y

Parsing NOAA studies:   0%|                                                                          | 0/100 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|██████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 4272.01it/s]

[2026-04-22 16:24:25,923][INFO] - Retrieved 100 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,10437,9101,"1,000 Year Ensemble Reconstructions of Tempera...",CLIMATE RECONSTRUCTIONS,950.0,-45.0,1000.0,1995.0,"(0.0, 90.0, -180.0, 180.0)",Calibration ensemble reconstructions of existi...,"[carbon cycle, sensitivity, Air Temperature Re...","David Frank, Jan Esper, Christoph Raible, Ulf ...","[{'Author': 'Frank, D.C., J. Esper, C.C. Raibl...","[[{'DataTableID': '19235', 'DataTableName': 'F...",[{'fundingAgency': 'Swiss National Science Fou...
1,11194,9632,"1,100 Year El Niño/Southern Oscillation (ENSO)...",CLIMATE RECONSTRUCTIONS,1050.0,-52.0,900.0,2002.0,"(-20.0, 20.0, 145.0, -80.0)",An index of canonical ENSO variability for the...,"[ENSO, Atmospheric and Oceanic Circulation Pat...","Jinbao Li, Shang-Ping Xie, Edward Cook, Gang H...","[{'Author': 'Li, J., S.-P. Xie, E.R. Cook, G. ...","[[{'DataTableID': '19791', 'DataTableName': 'e...",[{'fundingAgency': 'US National Science Founda...
2,14193,12194,1000 Year Composite Sea Surface Temperature Re...,PALEOCEANOGRAPHY,950.0,-46.0,1000.0,1996.0,"(56.66667, 69.48333, -18.1957, 18.36667)",A set of reconstructions of sea surface temper...,None,"Laura Cunningham, William Austin, Karen-Luise ...","[{'Author': 'Cunningham, L.K., Austin, W.E.N.,...","[[{'DataTableID': '24146', 'DataTableName': 'P...","[{'fundingAgency': 'European Commission', 'fun..."
3,42679,83754,1006-year reconstruction of Rossby wavenumber-5,CLIMATE RECONSTRUCTIONS,950.0,-55.0,1000.0,2005.0,"(0.0, 90.0, -180.0, 180.0)",None,[Atmospheric and Oceanic Circulation Patterns ...,"Ellie Broadman, Valerie Trouet, Kai Kornhuber","[{'Author': 'Broadman, Ellie, Kai Kornhuber, I...","[[{'DataTableID': '56946', 'DataTableName': 'W...",[{'fundingAgency': 'US National Science Founda...
4,36253,77512,10Be Chronology of Khoton Nuur Glacial Landfor...,CLIMATE RECONSTRUCTIONS,35000.0,16000.0,-33050.0,-14050.0,"(48.613232, 48.97233, 88.078977, 88.430928)",None,None,"Peter Strand, Aaron Putnam, Oyungerel Sambuu, ...","[{'Author': 'Strand, Peter D., Aaron E. Putnam...","[[{'DataTableID': '48957', 'DataTableName': 'K...",[{'fundingAgency': 'US National Science Founda...

In [ ]:
df_recent = ds.search_studies(recent=True, limit=25)
df_recent.head()

[2026-04-22 16:24:26,007][INFO] - search_studies: Limit set to 25.

[2026-04-22 16:24:26,008][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=25&recent=true

Parsing NOAA studies:   0%|                                                                           | 0/25 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 2500.42it/s]

[2026-04-22 16:24:27,252][WARNING] - Retrieved 25 studies, which is the specified limit. Consider increasing the limit parameter to fetch more studies.

[2026-04-22 16:24:27,253][INFO] - Retrieved 25 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,44619,85076,"Cueva de Asiul, Matienzo, Spain Stable Isotope...",CORALS AND SCLEROSPONGES,1091.0,-60.0,859.0,2010.0,"(43.32, 43.32, -3.59, -3.59)",The data set contains the raw d18O and d13C fo...,"[Precipitation Reconstruction, Atmospheric and...","Andrew Smith, Philip Barker, Mark Garnett, Arm...",[],"[[{'DataTableID': '59446', 'DataTableName': 'S...",[{'fundingAgency': 'UK Natural Environment Res...
1,44602,85056,"Botuvera Cave Oxygen Isotopes, Sr/Ca and Mg/Ca...",SPELEOTHEMS,114472.0,2143.0,-112522.0,-193.0,"(-27.22, -27.22, -49.16, -49.16)",None,"[Monsoon, Milankovitch, Heinrich Events]","Lucas Vasconcelos, Francisco Cruz, Juan Pablo ...","[{'Author': 'Lucas C. Vasconcelos, Francisco W...","[[{'DataTableID': '59427', 'DataTableName': 'B...",[{'fundingAgency': 'Coordination for the Impro...
2,44599,85055,Palynological data from Cretaceous and Paleoge...,POLLEN,NaN,NaN,NaN,NaN,"(-3.494607, -3.494607, -58.974049, -58.974049)","The letter ""P"" in the data table indicates tha...",[Vegetation Reconstruction],Debra Willard,"[{'Author': 'Marulanda, S.G., Rodrigues, F.C.G...","[[{'DataTableID': '59426', 'DataTableName': 'A...",[{'fundingAgency': 'United States Geological S...
3,44579,85075,Great Plains Low-Level Jet 300 Year Wind and M...,CLIMATE RECONSTRUCTIONS,260.0,-72.0,1690.0,2022.0,"(30.0, 42.0, -102.0, -92.0)",Tree-ring-based reconstruction of May-June-Jul...,[Atmospheric and Oceanic Circulation Patterns ...,"Erika Wise, Matthew Dannenberg",[{'Author': 'Erika K. Wise and Matthew P. Dann...,"[[{'DataTableID': '59411', 'DataTableName': 'U...",[{'fundingAgency': 'US National Science Founda...
4,44572,85023,Dannenberg - Buckhorn Mountain Update - PIPO -...,TREE RING,359.0,-70.0,1591.0,2020.0,"(43.78, 43.78, -103.6, -103.6)",this is an update of sd002,"[PIPO, ponderosa pine, western yellow pine, Pi...","Matthew Dannenberg, Erika Wise, None Harris, A...",[],"[[{'DataTableID': '59386', 'DataTableName': 'S...",[{'fundingAgency': 'US National Science Founda...

In [ ]:
### Limit up to first 10 results
df_limit = ds.search_studies(earliest_year=12000, time_format="BP", time_method="overAny", limit=10)
df_limit.head()

### Skip the first 10 results (i.e., get results 11-20)
df_skip = ds.search_studies(earliest_year=12000, time_format="BP", time_method="overAny", limit=10, skip=10)
df_skip.head()

[2026-04-22 16:24:27,291][INFO] - search_studies: Limit set to 10.

[2026-04-22 16:24:27,291][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=10&earliestYear=12000&timeFormat=BP&timeMethod=overAny

Parsing NOAA studies:   0%|                                                                           | 0/10 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 4924.05it/s]

[2026-04-22 16:24:28,305][WARNING] - Retrieved 10 studies, which is the specified limit. Consider increasing the limit parameter to fetch more studies.

[2026-04-22 16:24:28,306][INFO] - Retrieved 10 studies.

[2026-04-22 16:24:28,311][INFO] - search_studies: Limit set to 10.

[2026-04-22 16:24:28,312][INFO] - search_studies: Input Query includes geographical bounds. Inspect the results to ensure they match your intended region as one study can contain sites across various parts of the world.

Request URL: https://www.ncei.noaa.gov/access/paleo-search/study/search.json?dataPublisher=NOAA&limit=10&skip=10&earliestYear=12000&timeFormat=BP&timeMethod=overAny

Parsing NOAA studies:   0%|                                                                           | 0/10 [00:00<?, ?it/s]

Parsing NOAA studies: 100%|████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 9639.86it/s]

[2026-04-22 16:24:29,243][WARNING] - Retrieved 10 studies, which is the specified limit. Consider increasing the limit parameter to fetch more studies.

[2026-04-22 16:24:29,243][INFO] - Retrieved 10 studies.

,StudyID,XMLID,StudyName,DataType,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,"Coverage [S, N, W, E]",StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding
0,9896,8788,"200KYr Midge Temperature, Diatom pH, and C/N Data",PALEOLIMNOLOGY,200000,907,-198050,1043,"(70.558, 70.558, -68.95, -68.95)","Multiproxy sediment data from Lake CF8, Baffin...","[Arctic, Air Temperature Reconstruction]","Yarrow Axford, Jason Briner, Colin Cooke, Donn...","[{'Author': 'Axford, Y., J.P. Briner, C.A. Coo...","[[{'DataTableID': '18746', 'DataTableName': 'C...",[{'fundingAgency': 'US National Science Founda...
1,33872,75532,2017 Florida Bay Sr/Ca and d18O Data during Hu...,CORALS AND SCLEROSPONGES,-67,-67,2017,2017,"(24.9621, 24.9621, -80.801467, -80.801467)",Seawater Sr/Ca and oxygen isotopes to complem...,None,"K. Halimeda Kilbourne, Johan Schijf, Hunter Hu...","[{'Author': 'Khare, Agraj, Hunter P. Hughes, K...","[[{'DataTableID': '46662', 'DataTableName': 'O...",[{'fundingAgency': 'US National Science Founda...
2,2605,1676,340 KYr SW Pacific d18O Data and Mg/Ca-based S...,PALEOCEANOGRAPHY,340830,1951,-338880,-1,"(-45.53, -45.53, 174.93, 174.93)",,[Sea Surface Temperature Reconstruction],"Katharina Pahnke, Rainer Zahn, Henry Elderfiel...","[{'Author': 'Shackleton, N.J.', 'Title': 'The ...","[[{'DataTableID': '4289', 'DataTableName': 'MD...",[]
3,2614,1685,350 KYr Sea Level Reconstruction and Foraminif...,PALEOCEANOGRAPHY,361500,1000,-359550,950,"(2.25, 2.25, -90.95, -90.95)",,[Sea Level Reconstruction],"David Lea, Pamela Martin, Dorothy Pak, Howard ...","[{'Author': 'Lea, D.W., P.A. Martin, D.K. Pak,...","[[{'DataTableID': '4301', 'DataTableName': 'TR...",[]
4,14190,12191,600 Year Ensemble Climate Reconstructions and ...,CLIMATE RECONSTRUCTIONS,550,-61,1400,2011,"(45.0, 85.0, -180.0, 180.0)","Ensemble Climate Reconstructions, input data f...",[Air Temperature Reconstruction],"Martin Tingley, Peter Huybers","[{'Author': 'Tingley, M.P. and P. Huybers', 'T...","[[{'DataTableID': '24136', 'DataTableName': 'T...",[{'fundingAgency': 'US National Science Founda...

In [ ]:
import pyleotups as pt
ds = pt.PangaeaDataset()

### Can use either DOI strings or numeric IDs (extracted from DOIs)
df = ds.search_studies(
    study_ids=["10.1594/PANGAEA.830587", "10.1594/PANGAEA.830588"]
)
df.head()

df = ds.search_studies(
    study_ids=[830587, 830588]
)
df.head()

[2026-04-22 16:24:29,297][INFO] - Registering Study 830587 via direct lookup.

[2026-04-22 16:24:32,550][INFO] - Registering Study 830588 via direct lookup.

[2026-04-22 16:24:35,410][INFO] - Retrived 2 studies

[2026-04-22 16:24:35,414][INFO] - Retrived 2 studies

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,830587,(Table 2) Age determination of sediment core M...,98.0,1950.0,0.0,1852.0,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
1,830588,(Table 3) Lead 214 and Lead 210 concentration ...,NaN,NaN,NaN,NaN,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None

In [ ]:
df = ds.search_studies(search_text="Stable oxygen and carbon isotopes", limit = 5)
df.head()

[2026-04-22 16:24:35,445][INFO] - Limit set to 5

{'q': 'Stable oxygen and carbon isotopes', 'bbox': None, 'limit': 5, 'offset': 0}

[2026-04-22 16:24:54,054][INFO] - Retrived 7 studies

[2026-04-22 16:24:54,060][WARNING] - The search contains dataset(s) [759625, 946916] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,830587,(Table 2) Age determination of sediment core M...,98.0,1950.0,0.0,1852.0,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
1,830588,(Table 3) Lead 214 and Lead 210 concentration ...,NaN,NaN,NaN,NaN,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
2,930941,Benthic stable carbon and oxygen isotopes of C...,4040447.0,2947.0,-4038497.0,-997.0,ODP Leg 130 - Site 806B benthic stable carbon ...,"[benthic d13C, benthic d18O, equatorial Pacifi...","Bickert, Torsten","Bickert, Torsten (2026): Benthic stable carbon...",[130-806B],[{'name': 'Integrated Ocean Drilling Program /...,None
3,936448,Oxygen and carbon stable isotopes of Neogloboq...,243000.0,7620.0,-241050.0,-5670.0,Stable isotope data on the near-surface polar ...,"[Depth/age, Snorri Drift, stabe isotopes]","Andrews, John T","Andrews, John T (2021): Oxygen and carbon stab...",[MD99-2323],[],None
4,906181,Carbon and oxygen stable isotopes measured on ...,849790.0,14930.0,-847840.0,-12980.0,High latitude deep water upwelling has the pot...,"[Bering Sea, CO2, Glacial, Sea ice, subarctic,...","Worne, Savannah","Worne, Savannah (2019): Carbon and oxygen stab...","[323-U1343A, 323-U1343C, 323-U1343E]",[{'name': 'Integrated Ocean Drilling Program /...,None

In [ ]:
df = ds.search_studies(variable_name=["Pulleniatina obliquiloculata δ13C", "Pulleniatina obliquiloculata δ18O"], limit = 5)
df.head()

[2026-04-22 16:24:54,096][INFO] - Limit set to 5

{'q': 'parameter:Pulleniatina obliquiloculata δ13C parameter:Pulleniatina obliquiloculata δ18O', 'bbox': None, 'limit': 5, 'offset': 0}

[2026-04-22 16:25:13,175][INFO] - Retrived 12 studies

[2026-04-22 16:25:13,189][WARNING] - The search contains dataset(s) [759625, 946916] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,830587,(Table 2) Age determination of sediment core M...,98.0,1950.0,0.0,1852.0,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
1,830588,(Table 3) Lead 214 and Lead 210 concentration ...,NaN,NaN,NaN,NaN,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
2,930941,Benthic stable carbon and oxygen isotopes of C...,4040447.0,2947.0,-4038497.0,-997.0,ODP Leg 130 - Site 806B benthic stable carbon ...,"[benthic d13C, benthic d18O, equatorial Pacifi...","Bickert, Torsten","Bickert, Torsten (2026): Benthic stable carbon...",[130-806B],[{'name': 'Integrated Ocean Drilling Program /...,None
3,936448,Oxygen and carbon stable isotopes of Neogloboq...,243000.0,7620.0,-241050.0,-5670.0,Stable isotope data on the near-surface polar ...,"[Depth/age, Snorri Drift, stabe isotopes]","Andrews, John T","Andrews, John T (2021): Oxygen and carbon stab...",[MD99-2323],[],None
4,906181,Carbon and oxygen stable isotopes measured on ...,849790.0,14930.0,-847840.0,-12980.0,High latitude deep water upwelling has the pot...,"[Bering Sea, CO2, Glacial, Sea ice, subarctic,...","Worne, Savannah","Worne, Savannah (2019): Carbon and oxygen stab...","[323-U1343A, 323-U1343C, 323-U1343E]",[{'name': 'Integrated Ocean Drilling Program /...,None

In [ ]:
df = ds.search_studies(investigators=["Khider, D"], limit = 5)
df.head()

[2026-04-22 16:25:13,245][INFO] - Limit set to 5

{'q': 'author:Khider, D', 'bbox': None, 'limit': 5, 'offset': 0}

[2026-04-22 16:25:21,651][INFO] - Retrived 15 studies

[2026-04-22 16:25:21,657][WARNING] - The search contains dataset(s) [759625, 946916, 830589, 897517] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,830587,(Table 2) Age determination of sediment core M...,98.0,1950.0,0.0,1852.0,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
1,830588,(Table 3) Lead 214 and Lead 210 concentration ...,NaN,NaN,NaN,NaN,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
2,930941,Benthic stable carbon and oxygen isotopes of C...,4040447.0,2947.0,-4038497.0,-997.0,ODP Leg 130 - Site 806B benthic stable carbon ...,"[benthic d13C, benthic d18O, equatorial Pacifi...","Bickert, Torsten","Bickert, Torsten (2026): Benthic stable carbon...",[130-806B],[{'name': 'Integrated Ocean Drilling Program /...,None
3,936448,Oxygen and carbon stable isotopes of Neogloboq...,243000.0,7620.0,-241050.0,-5670.0,Stable isotope data on the near-surface polar ...,"[Depth/age, Snorri Drift, stabe isotopes]","Andrews, John T","Andrews, John T (2021): Oxygen and carbon stab...",[MD99-2323],[],None
4,906181,Carbon and oxygen stable isotopes measured on ...,849790.0,14930.0,-847840.0,-12980.0,High latitude deep water upwelling has the pot...,"[Bering Sea, CO2, Glacial, Sea ice, subarctic,...","Worne, Savannah","Worne, Savannah (2019): Carbon and oxygen stab...","[323-U1343A, 323-U1343C, 323-U1343E]",[{'name': 'Integrated Ocean Drilling Program /...,None

In [ ]:
df = ds.search_studies(
    search_text="Stable oxygen and carbon isotopes",
    variable_name=["Pulleniatina obliquiloculata δ13C", "Pulleniatina obliquiloculata δ18O"],
    investigators="Khider, D",
    limit = 5
)
df.head()

[2026-04-22 16:25:21,714][INFO] - Limit set to 5

{'q': 'Stable oxygen and carbon isotopes author:Khider, D parameter:Pulleniatina obliquiloculata δ13C parameter:Pulleniatina obliquiloculata δ18O', 'bbox': None, 'limit': 5, 'offset': 0}

[2026-04-22 16:25:26,458][INFO] - Retrived 16 studies

[2026-04-22 16:25:26,469][WARNING] - The search contains dataset(s) [759625, 946916, 830589, 897517] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,830587,(Table 2) Age determination of sediment core M...,98.0,1950.0,0.0,1852.0,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
1,830588,(Table 3) Lead 214 and Lead 210 concentration ...,NaN,NaN,NaN,NaN,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
2,930941,Benthic stable carbon and oxygen isotopes of C...,4040447.0,2947.0,-4038497.0,-997.0,ODP Leg 130 - Site 806B benthic stable carbon ...,"[benthic d13C, benthic d18O, equatorial Pacifi...","Bickert, Torsten","Bickert, Torsten (2026): Benthic stable carbon...",[130-806B],[{'name': 'Integrated Ocean Drilling Program /...,None
3,936448,Oxygen and carbon stable isotopes of Neogloboq...,243000.0,7620.0,-241050.0,-5670.0,Stable isotope data on the near-surface polar ...,"[Depth/age, Snorri Drift, stabe isotopes]","Andrews, John T","Andrews, John T (2021): Oxygen and carbon stab...",[MD99-2323],[],None
4,906181,Carbon and oxygen stable isotopes measured on ...,849790.0,14930.0,-847840.0,-12980.0,High latitude deep water upwelling has the pot...,"[Bering Sea, CO2, Glacial, Sea ice, subarctic,...","Worne, Savannah","Worne, Savannah (2019): Carbon and oxygen stab...","[323-U1343A, 323-U1343C, 323-U1343E]",[{'name': 'Integrated Ocean Drilling Program /...,None

In [ ]:
df = ds.search_studies(
    min_lat=-10, max_lat=10,
    min_lon=120, max_lon=160
)
df.head()

[2026-04-22 16:25:26,538][INFO] - Limit set to 100

{'q': '', 'bbox': (120, -10, 160, 10), 'limit': 100, 'offset': 0}

[2026-04-22 16:29:38,363][INFO] - Retrived 116 studies

[2026-04-22 16:29:38,405][WARNING] - The search contains dataset(s) [759625, 946916, 830589, 897517, 954692, 971539, 933340, 983391, 887764, 980726, 818970, 950075, 902662, 874319, 899182, 922693, 897104, 839414, 928247, 943130, 921278, 983489, 874687, 924044, 984064, 945550, 807876, 910198, 971967, 835082, 908303, 946134, 770334, 815840, 895987, 922660, 743464, 846405, 952157, 864735, 899188, 899217, 754747, 871885, 824489, 860795, 858091, 754276, 854018, 963567, 877438, 921708, 836359, 786708, 723906, 831190, 820607, 779281, 779239, 779189, 779168, 779059, 779020, 922183, 837186, 987417, 871963, 949555, 948194, 711722, 989939, 854775, 932504, 918714, 700006, 984785, 830815, 787036, 787065, 787043, 787060, 786920, 787094, 786948, 786935, 786992, 787055, 786900, 786805, 786847, 736687, 926072, 854781, 854688, 839181] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,830587,(Table 2) Age determination of sediment core M...,98.0,1950.0,0.0,1852.0,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
1,830588,(Table 3) Lead 214 and Lead 210 concentration ...,NaN,NaN,NaN,NaN,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
2,930941,Benthic stable carbon and oxygen isotopes of C...,4040447.0,2947.0,-4038497.0,-997.0,ODP Leg 130 - Site 806B benthic stable carbon ...,"[benthic d13C, benthic d18O, equatorial Pacifi...","Bickert, Torsten","Bickert, Torsten (2026): Benthic stable carbon...",[130-806B],[{'name': 'Integrated Ocean Drilling Program /...,None
3,936448,Oxygen and carbon stable isotopes of Neogloboq...,243000.0,7620.0,-241050.0,-5670.0,Stable isotope data on the near-surface polar ...,"[Depth/age, Snorri Drift, stabe isotopes]","Andrews, John T","Andrews, John T (2021): Oxygen and carbon stab...",[MD99-2323],[],None
4,906181,Carbon and oxygen stable isotopes measured on ...,849790.0,14930.0,-847840.0,-12980.0,High latitude deep water upwelling has the pot...,"[Bering Sea, CO2, Glacial, Sea ice, subarctic,...","Worne, Savannah","Worne, Savannah (2019): Carbon and oxygen stab...","[323-U1343A, 323-U1343C, 323-U1343E]",[{'name': 'Integrated Ocean Drilling Program /...,None